### PR TITLE
Use builder

### LINKED ISSUE #42: Switch to docker-builder instead of helmfile image
- This PR superseeds #39 and #40 
- Initial reasons to use the `docker-helmfile`:
  - [Must have] Ruby 3.0.x (latest version available for the apt package)
  - [Nice to have] Reuse the same image as most of the other jobs to ensure it is cached (faster spins up when autoscaling)

=> To switch to `docker-builder`, we should define a `.tools-version` in this repo with the specified Ruby version and install it when needed (for the pipelines that needs ruby of course)

_Originally posted by @dduportal in https://github.com/jenkins-infra/infra-reports/issues/41#issuecomment-1186880318_

### PR DESCRIPTION
**Pull request by halkeye**
Closes #42

### CODE REVIEW

**Comment by halkeye** [comment]
@dduportal @timja 

Github app needs access to projects, but otherwise working!

**Comment by timja** [comment]
> @dduportal @timja
> 
> Github app needs access to projects, but otherwise working!

I have added read-only access to projects for jenkins-infra-reports

**Comment by halkeye** [comment]
I can't trigger a re run from my phone :(

**Comment by halkeye** [comment]
wait i can close and reopen

**Comment by timja** [comment]
> wait i can close and reopen

i had manually triggered it anyway :tong

**Comment by halkeye** [comment]
> I have added read-only access to projects for jenkins-infra-reports

```
  errors: [
09:58:22        {
09:58:22          type: 'FORBIDDEN',
09:58:22          path: [ 'organization', 'project' ],
09:58:22          extensions: { saml_failure: false },
09:58:22          locations: [ { line: 4, column: 5 } ],
09:58:22          message: 'Resource not accessible by integration'
09:58:22        }
09:58:22      ],
```

Did you add projects? or organization projects? I had to do read_org to make org projects work

image

**Comment by timja** [comment]
I did repository projects, I've added organization projects

**Review by timja — APPROVED** [review]

**Pull request merged**
