### PR TITLE
Update Ruby and node

### PR DESCRIPTION
**Pull request by NotMyFault**
Bump the docker image to the newest version of ruby, and rebundles the gem files.

### CODE REVIEW

**Comment by NotMyFault** [comment]
> 16:17:06  ERROR: ‘JenkinsAgentPodTemplate.yaml’ has been modified in an untrusted revision

Tried to replay on infra.ci, but it refuses my change :(

**Comment by lemeurherve** [comment]
> it refuses my change :(

Same.

**Comment by dduportal** [comment]
Output log for the "Forks Report":

- `bundle install` reports a different patch version. Seems not blocking at all (I assume it's the bundle version installed by `asdf` along with Ruby)

```
Bundler 2.4.10 is running, but your lockfile was generated with 2.4.1. Installing Bundler 2.4.1 and restarting using that version.
```

- No warning, nor error in the ruby execution

Same for "Permissions Report" ✅

**Review by dduportal — APPROVED** [review]
LGTM 👍

**Comment by dduportal** [comment]
You can merge when ready @NotMyFault

**Pull request merged**
